sohan01fw/Ghumfir

Frontend/.gitignore, Frontend/package-lock.json, Frontend/package.json, Frontend/src/App.jsx, Frontend/src/Components/map/LocationPin.jsx, Frontend/src/Components/map/Map.jsx, Frontend/src/pages/About.jsx
=> integrating google map

Backend/.env, Backend/package-lock.json, Backend/package.json, Backend/src/Db/dbConn.ts, Backend/src/index.ts, Backend/src/routes/auth.ts
setuping google auth configuration in node js using package called passport and initialing typos and routes for it.
=> googleAuth-configuration

Backend/src/Controllers/TripPlanController.ts, Backend/src/Controllers/UserController.ts, Backend/src/Db/Models/TripPlan.model.ts, Backend/src/Db/Models/User.model.ts, Backend/src/Db/dbConn.ts, Backend/src/index.ts, Backend/src/routes/UserRoute.ts, Backend/tsconfig.json, Backend/types/index.d.ts
inserting Data to db and fixing some typos in typescript file and confguring ts modules
=> inserting userData to db and configure some types

Backend/src/Controllers/UserController.ts, Backend/src/index.ts, Backend/src/routes/UserRoute.ts
some changes on route handling file and along with cors restrictions within the browsers.
=> changes on route handling file

Backend/src/Controllers/ItineriesController.ts, Backend/src/Controllers/UserController.ts, Backend/src/index.ts, Backend/src/routes/UserRoute.ts, Backend/src/routes/tripPlanRoute.ts
getting logged in users details with itineries created by user
=> get users and itineries

Frontend/.gitignore, Frontend/package-lock.json, Frontend/package.json, Frontend/src/App.jsx, Frontend/src/Components/map/GoogleMap.jsx, Frontend/src/main.jsx, Frontend/src/pages/Home/Blog.jsx, Frontend/src/pages/Home/MapView.jsx
integrating map with new google map api and fixing the vite .env file accessing undefined error.
=> integrating map

Frontend/index.html, Frontend/package-lock.json, Frontend/package.json, Frontend/src/Components/map/InputLocation.css, Frontend/src/Components/map/InputLocation.jsx, Frontend/src/pages/Home/MapView.jsx
Here i enable place api from gcp where i integrate to my react input field to list out places suggestion using library called use palces autocomplete to give dropdown list like suggestion of places and finally displaying lat and lang of selected palces in console.
=> adding places search inputfield

Frontend/src/Components/TipsDetails/TripDetails.jsx, Frontend/src/Components/map/InputLocation.jsx, Frontend/src/main.jsx
creating data structure from fetching places data and optimizing the data fetching type and rendering location.
Also fixing some double rendering bug in react by disabling strict-mode from the root file of react .
=> creating data structure of places details

Backend/src/Controllers/ItineriesController.ts, Backend/src/index.ts, Frontend/package-lock.json, Frontend/package.json, Frontend/src/Components/TipsDetails/Trips.jsx, Frontend/src/Store/ItineriesContext.jsx
sending itineraries information like geo code place id and start date and end date to server using package called axios.
And some dynamic customization in cors policy.
=> sending itinerariesInfo to server

Backend/src/Controllers/ItineriesController.ts, Backend/src/Db/Models/itineraries.model.ts, Backend/types/index.d.ts, Frontend/package-lock.json, Frontend/package.json, Frontend/src/Components/TipsDetails/Trips.jsx, Frontend/src/Components/map/InputLocation.jsx
customize and updating itinerary model accroding to data comming from client side.
=> updating and changing itineraries-model

Backend/src/Controllers/ItineriesController.ts, Backend/src/routes/tripPlanRoute.ts, Frontend/src/App.jsx, Frontend/src/Components/TipsDetails/TripDetails.jsx, Frontend/src/Components/TipsDetails/Trips.jsx, Frontend/src/Store/ItineriesContext.jsx
implementing dynamic routes in client and server using params to fetch the data easily in future.
=> implementing dynamic routes using params

Backend/src/Controllers/ItineriesController.ts, Backend/src/routes/tripPlanRoute.ts, Frontend/src/Components/TipsDetails/TripDetails.jsx, Frontend/src/Store/ItineriesContext.jsx
getting data in client page by passing the itenaraies id through params and fetching from data using that id and sending as res ponse to client side.
=> getting itiinfo data in client page

Backend/src/Controllers/ItineriesController.ts, Backend/src/Db/Models/itineraries.model.ts
modifying itinerariesModel to get to use in to populate the userInfo with it along with it's controller where there the function of getting itinerary.
=> populating userInfo with itiInfo

Frontend/src/Components/TipsDetails/PlacesToVisit.jsx, Frontend/src/Components/TipsDetails/TripDetails.jsx, Frontend/src/Components/map/GoogleMaps.jsx, Frontend/src/lib/Map/DisplayPlaces.jsx, Frontend/src/lib/Map/MapLocation.jsx
rendering and displaying places info in displace page.js page where i just render out the thing so that it will help to work further
=> rendering placesInfo with map

Backend/src/Controllers/ItineriesController.ts, Backend/src/Controllers/UserController.ts, Backend/src/Db/Models/User.model.ts, Backend/src/Db/Models/itiInfoDetails/allItiDetails.model.ts, Backend/src/Db/Models/itineraries.model.ts, Backend/src/routes/UserRoute.ts, Backend/types/index.d.ts
optimizing all models i.e user and itineraries and creating itidetailsInfo model for to store multiple model at once in future
=> creating itidetailsInfo model and optimzing all models

Backend/src/Controllers/itiDetailsInfoController.ts, Backend/src/Db/Models/itiInfoDetails/allItiDetails.model.ts, Backend/src/routes/tripPlanRoute.ts, Backend/types/index.d.ts
inserting multiple arrray of object data at once like 20 of them so i can fetch and use it in following application use
=> inserting manyData at once

Backend/src/Controllers/itiDetailsInfoController.ts, Backend/src/Db/Models/itiInfoDetails/allItiDetails.model.ts, Backend/src/Db/Models/itineraries.model.ts, Backend/types/index.d.ts, Frontend/src/Store/ItineriesContext.jsx, Frontend/src/lib/Map/DisplayPlaces.jsx
send itiDetails data which is like 20 of them sending to server to save to db and fetch from it in future
=> sending many list of data to server

Backend/src/Controllers/ItineriesController.ts, Backend/src/Controllers/itiDetailsInfoController.ts, Backend/src/index.ts, Backend/src/routes/placeDetailsRoute.ts, Backend/src/routes/tripPlanRoute.ts, Frontend/src/Components/TipsDetails/TripDetails.jsx, Frontend/src/Store/ItineriesContext.jsx, Frontend/src/lib/Map/DisplayPlaces.jsx
create new route for placeDetails and tryin to fixin some bugs but cloudn't
=> modidfied placeDetails route

Backend/src/Controllers/ItineriesController.ts, Backend/src/Controllers/itiDetailsInfoController.ts
fixing updating itiDetails in userItineraries model
=> fixed updating itiDetails

Frontend/src/Components/TipsDetails/TripDetails.jsx, Frontend/src/lib/Map/DisplayPlaces.jsx
fixing error of while displaying map in trip details page
=> fix google map display error

Backend/src/Controllers/ItineriesController.ts, Frontend/src/lib/Map/DisplayPlaces.jsx
getting and fetching data successfully in client side
=> getting populated place data

Frontend/src/Components/TipsDetails/TripDetails.jsx, Frontend/src/Components/map/GoogleMaps.jsx, Frontend/src/Store/ItineriesContext.jsx, Frontend/src/lib/Map/DisplayPlaces.jsx
ok displaying and fetching the map data which is created by user dynamically.
=> dynamically display and fetch map data

Backend/src/Controllers/itiDetailsInfoController.ts, Backend/src/Db/Models/itiInfoDetails/allItiDetails.model.ts, Backend/types/index.d.ts, Frontend/src/Components/TipsDetails/Overview.jsx, Frontend/src/Components/TipsDetails/TripDetails.jsx, Frontend/src/Components/map/GoogleMaps.jsx, Frontend/src/lib/Map/DisplayPlaces.jsx
fixing multiple api call while inserting data to db from client side. And fixing rerendering components
=> fixing multiple api call

Frontend/index.html, Frontend/src/App.jsx, Frontend/src/Components/map/GoogleMaps.jsx, Frontend/src/Components/map/InputLocation.jsx, Frontend/src/lib/Map/DisplayPlaces.jsx
optimizng googel places details response by adding some specific parameters about locations and fixing some api related bugs.
=> optimizing google places details response

Backend/src/Controllers/itiDetailsInfoController.ts, Backend/src/Db/Models/itiInfoDetails/allItiDetails.model.ts, Backend/src/index.ts, Backend/types/index.d.ts, Frontend/index.html, Frontend/src/Components/map/InputLocation.jsx, Frontend/src/lib/Map/DisplayPlaces.jsx
modified the images and reviews data structure in itidetailsmodel
=> modified the images and reviews data structure

Backend/src/Db/Models/itiInfoDetails/allItiDetails.model.ts, Backend/types/index.d.ts, Frontend/src/lib/Map/DisplayPlaces.jsx
fixing url of images from placedetails in db and optimizing api hit from client side while inserting places details.
=> fixing url of images from placedetails in db

Backend/src/Controllers/ItineriesController.ts, Backend/src/Db/Models/itineraries.model.ts, Backend/src/routes/tripPlanRoute.ts, Backend/types/index.d.ts
getting all itinerariesData with user for to display it in home page.
=> getting all itinerariesData with user

Backend/package-lock.json, Backend/package.json, Backend/src/Db/Models/User.model.ts, Backend/src/index.ts, Backend/types/index.d.ts
changes in userRoute for auth configuration and updating usermodel
=> changes in userRoute for auth config

Backend/package-lock.json, Backend/package.json, Backend/src/Controllers/UserController.ts, Backend/src/Db/Models/User.model.ts, Backend/src/routes/UserRoute.ts, Backend/types/index.d.ts
implementing user registration with hasing password using bcrypt library with SHA256 hashing algorithm.
=> implementing user registration

Backend/package-lock.json, Backend/package.json, Backend/src/Db/Models/User.model.ts, Backend/src/index.ts, Backend/utils/generateToken.ts, Backend/utils/hashedAnything.ts
gnerating jwt token and solving config error
=> gnerating jwt token and solving config error

Backend/src/Controllers/UserController.ts, Backend/src/Db/Models/User.model.ts, Backend/src/utils/hashedAnything.ts
implementing refresh token methods with somechanges on hashing code to by adding salt round and fixing bugs
=> implementing refresh token methods

Backend/src/Controllers/UserController.ts, Backend/src/Db/Models/User.model.ts, Backend/src/routes/UserRoute.ts
setting a setup for login user with some strong validation and configurations
=> setting a setup for login user

Backend/src/Controllers/UserController.ts, Backend/src/Db/Models/User.model.ts, Backend/src/index.ts
setting up cookies with tokens and doing some debugging and validation .
=> setting up cookies with tokens

Backend/src/Controllers/UserController.ts, Backend/src/Middleware/userMiddleware.ts, Backend/src/index.ts, Backend/src/routes/UserRoute.ts
=> setup logout user

Backend/src/Controllers/UserController.ts, Backend/src/Middleware/userMiddleware.ts, Backend/src/index.ts, Backend/src/routes/UserRoute.ts
features logout complete with other debugging .
=> features logout complete

Backend/src/Db/Models/User.model.ts
=> fix user model error

Frontend/src/App.jsx, Frontend/src/Components/Footer/Footer.css, Frontend/src/Components/Footer/Footer.jsx, Frontend/src/Components/TipsDetails/TripDetails.css
aligned the tripdetails page footer
=> updated tripdetailspage footer

Frontend/index.html, Frontend/src/Components/TipsDetails/TripDetails.jsx, Frontend/src/lib/Map/DisplayPlaces.jsx
displaying image and modifing code
=> displaying image and modifing code

Backend/src/Controllers/itiDetailsInfoController.ts, Frontend/src/Components/map/GoogleMaps.jsx, Frontend/src/Store/ItineriesContext.jsx, Frontend/src/lib/Map/DisplayPlaces.jsx
=> fix instant display of marker

Frontend/package-lock.json, Frontend/package.json, Frontend/src/Components/TipsDetails/TripDetails.css, Frontend/src/Components/map/GoogleMaps.css, Frontend/src/Components/map/GoogleMaps.jsx
adding display info marker with tooltip
=> adding display info marker with tooltip

Frontend/src/App.jsx, Frontend/src/Components/map/GoogleMaps/GoogleMaps.jsx, Frontend/src/Components/map/InputLocation/InputLocation.jsx, Frontend/src/Components/map/MapPlacesDisplay/DisplayPlaces.jsx, Frontend/src/Store/ItineriesContext.jsx, Frontend/src/Store/Reducer.jsx, Frontend/src/lib/Actions/ServerPostActions/PostItiDetails.js, Frontend/src/pages/TripDetails/TripDetails.jsx, Frontend/src/pages/Trips/Trips.jsx, Frontend/src/utils/exportItem.js
config with renew react context to related files and folder for efficient and scalable solution
=> config with renew react context

Backend/src/Controllers/ItineriesController.ts, Backend/src/Controllers/PlacesController.ts, Backend/src/Db/Models/Places.model.ts, Backend/src/index.ts, Backend/src/routes/ItinerariesRoute.ts, Backend/src/routes/PlacesRoute.ts, Backend/types/index.d.ts
create and configuring places model
=> create and configuring places model

Backend/src/Controllers/ItineriesController.ts, Backend/src/Controllers/PlacesController.ts, Backend/src/Db/Models/Places.model.ts, Backend/src/routes/PlacesRoute.ts, Backend/types/index.d.ts, Frontend/src/lib/Actions/ServerGetActions/getPlaces.js, Frontend/src/lib/Actions/ServerPostActions/PostPlaces.js, Frontend/src/pages/TripPlaces/TripPlaces.jsx, Frontend/src/pages/Trips/Trips.jsx
updating places-model-and client tripplacesOp
=> updating places-model-and client tripplacesOp

Backend/src/Controllers/ItineriesController.ts, Backend/src/Controllers/PlacesController.ts, Frontend/src/App.jsx, Frontend/src/lib/Actions/ServerGetActions/getPlaces.js, Frontend/src/lib/Actions/ServerPostActions/PostItiDetails.js, Frontend/src/lib/Actions/ServerPostActions/PostPlaces.js, Frontend/src/pages/Trips/Trips.jsx
get all data for places page so to displaying in client side for futhur navigation.
=> get all data for places page

Frontend/src/App.jsx, Frontend/src/lib/ui/NestedLink.jsx, Frontend/src/pages/TripPlaces/TripPlaces.jsx
display all places and also integrating routing to trip details page
=> display all places and also integrating routing

Backend/src/Controllers/PlacesController.ts, Backend/src/Db/Models/Places.model.ts, Backend/types/index.d.ts, Frontend/src/Components/map/GoogleMaps/GoogleMaps.jsx, Frontend/src/Components/map/InputLocation/Places/PlacesInputLoc.css, Frontend/src/Components/map/InputLocation/Places/PlacesInputLoc.jsx, Frontend/src/lib/Actions/ServerGetActions/getPlaces.js, Frontend/src/lib/Actions/ServerPostActions/PostPlaces.js, Frontend/src/pages/TripPlaces/TripPlaces.css, Frontend/src/pages/TripPlaces/TripPlaces.jsx, Frontend/src/pages/Trips/Trips.jsx
=> displaying data with marker

Backend/src/Controllers/itiDetailsInfoController.ts, Backend/src/Db/Models/Places.model.ts, Backend/src/Db/Models/allItiDetails.model.ts, Backend/src/routes/placeDetailsRoute.ts, Backend/types/index.d.ts, Frontend/src/Components/Navigation/SideBar/IconSideBar/IconSideBar.jsx, Frontend/src/Components/Navigation/SideBar/SideBar.css, Frontend/src/Components/Navigation/SideBar/SideBar.jsx, Frontend/src/Components/map/DisplayPlaceDetails/DisplayPlaceDetails.jsx, Frontend/src/Components/ui/Accordation.css, Frontend/src/Components/ui/Accordation.jsx, Frontend/src/pages/TripDetails/TripDetails.css, Frontend/src/pages/TripDetails/TripDetails.jsx
fix ui bug and modified itiplacedetail model
=> fix ui bug and modified itiplacedetail model

Backend/src/Controllers/itiDetailsInfoController.ts, Backend/src/routes/placeDetailsRoute.ts, Frontend/src/Components/ui/Accordation.jsx, Frontend/src/lib/Actions/ServerGetActions/GetPlacesItiId.js, Frontend/src/lib/Actions/ServerPostActions/PostPlacesItiId.js
features to add placeItiDetails
=> features to add placeItiDetails

Frontend/src/Components/map/InputLocation/InputLocation.css, Frontend/src/Components/map/InputLocation/InputLocation.jsx, Frontend/src/Components/map/InputLocation/Places/PlacesInputLoc.css, Frontend/src/Components/map/InputLocation/Places/PlacesInputLoc.jsx, Frontend/src/pages/Trips/Trips.css, Frontend/src/pages/Trips/Trips.jsx
=> updated tripspage ui

Backend/src/Controllers/itiDetailsInfoController.ts, Backend/src/routes/placeDetailsRoute.ts, Frontend/src/Components/Navigation/SideBar/IconSideBar/IconSideBar.css, Frontend/src/Components/Navigation/SideBar/IconSideBar/IconSideBar.jsx, Frontend/src/Components/map/GoogleMaps/GoogleMaps.jsx, Frontend/src/Components/ui/Accordation.css, Frontend/src/Components/ui/Accordation.jsx, Frontend/src/Components/ui/AccordionExplore.jsx, Frontend/src/Store/Reducer.jsx, Frontend/src/pages/TripDetails/TripDetails.css, Frontend/src/pages/TripDetails/TripDetails.jsx, Frontend/src/pages/TripPlaces/TripPlaces.jsx
update ui and modified functionality
=> update ui and modified functionality

Backend/src/Controllers/UserController.ts, Backend/src/Db/Models/User.model.ts, Backend/src/Middleware/userMiddleware.ts, Backend/src/routes/UserRoute.ts
fixing backend auth config bug
=> fixing backend auth config bug

Frontend/src/App.jsx, Frontend/src/Components/Navigation/NavLinks/NavLinks.jsx, Frontend/src/Components/ui/AuthModel.jsx, Frontend/src/lib/Actions/ServerPostActions/RegistrationForm.js, Frontend/src/pages/Auth/Auth.jsx, Frontend/src/pages/Auth/Login.css, Frontend/src/pages/Auth/Login.jsx, Frontend/src/pages/Auth/SignUp.css, Frontend/src/pages/Auth/SignUp.jsx
update ui and add registration features
=> update ui and add registration features

Backend/src/Controllers/PlacesController.ts, Backend/src/Controllers/UserController.ts, Backend/src/Controllers/itiDetailsInfoController.ts, Backend/src/index.ts, Backend/src/routes/PlacesRoute.ts, Backend/src/routes/placeDetailsRoute.ts, Backend/src/utils/getRTandAT.ts, Frontend/package-lock.json, Frontend/package.json, Frontend/src/App.jsx, Frontend/src/Store/Reducer.jsx, Frontend/src/lib/Actions/ServerPostActions/LoginForm.js, Frontend/src/lib/Token.js, Frontend/src/main.jsx, Frontend/src/pages/Auth/Login.jsx, Frontend/src/pages/Trips/Trips.jsx
implement restricted route with login functionality
=> implement restricted route with login functionality

Backend/src/Controllers/UserController.ts, Backend/src/routes/UserRoute.ts, Backend/src/utils/getRTandAT.ts, Frontend/src/App.jsx, Frontend/src/lib/Actions/ServerGetActions/getAccessToken.js
=> renew access token logic

Frontend/index.html, Frontend/src/Components/map/InputLocation/InputLocation.jsx, Frontend/src/Store/Reducer.jsx, Frontend/src/lib/useToken.js, Frontend/src/pages/TripDetails/TripDetails.jsx, Frontend/src/pages/TripPlaces/TripPlaces.jsx, Frontend/src/pages/Trips/Trips.jsx
=> fix ui bug in trips page

Frontend/src/Components/Navigation/MainNavigation.jsx, Frontend/src/Components/Navigation/SideBar/IconSideBar/IconSideBar.jsx, Frontend/src/Components/ui/Accordation.jsx, Frontend/src/pages/TripDetails/TripDetails.css, Frontend/src/pages/TripDetails/TripDetails.jsx
=> fix nav ui of tripdetailspage

Backend/src/Controllers/BudgetController.ts, Backend/src/Middleware/userMiddleware.ts, Backend/src/routes/BudgetRoute.ts, Frontend/src/Components/TripDetails/Budget/Budget.jsx, Frontend/src/Components/ui/Budget/EditExpenseModel.jsx, Frontend/src/Components/ui/Budget/EditModel.jsx, Frontend/src/Store/Reducer.jsx, Frontend/src/lib/Actions/ServerPostActions/PostBudget.js
=> fix budget bugs

Frontend/src/App.jsx, Frontend/src/Components/Navigation/NavLinks/NavLinks.jsx, Frontend/src/Components/map/InputLocation/InputLocation.jsx, Frontend/src/Components/map/InputLocation/Places/PlacesInputLoc.jsx, Frontend/src/Components/ui/NestedLink.jsx, Frontend/src/lib/Actions/ServerPostActions/Airecomend.js, Frontend/src/pages/AiRecommend/AiRecommend.jsx, Frontend/src/pages/TripPlaces/TripPlaces.css, Frontend/src/pages/TripPlaces/TripPlaces.jsx
=> implementing ai algo

Backend/src/Controllers/PlacesController.ts, Backend/src/routes/PlacesRoute.ts, Frontend/src/Components/Navigation/TripPlaceNav/TripPlaceNav.jsx, Frontend/src/Components/ui/NestedLink.jsx, Frontend/src/lib/Actions/ServerGetActions/getAllPlaces.js, Frontend/src/pages/Home/Home.jsx, Frontend/src/pages/TripDetails/TripDetails.jsx, Frontend/src/utils/Hooks/placesHook/useGetImg.jsx
fixing bugs and hompages details
=> fixing bugs and hompages details

Frontend/src/lib/Actions/ServerPostActions/LoginForm.js, Frontend/src/lib/Actions/ServerPostActions/RegistrationForm.js, Frontend/src/pages/Auth/Login.jsx, Frontend/src/pages/Auth/SignUp.jsx
fix signup and login with added functionality
=> fix signup and login with added functionality

Backend/src/Controllers/UserController.ts, Backend/src/Middleware/userMiddleware.ts, Backend/src/routes/UserRoute.ts, Frontend/src/App.jsx, Frontend/src/Components/ui/AccountMenu.jsx, Frontend/src/pages/UserAccount/UserAccount.jsx
=> display user in navbar
